{$IFDEF VER80}
	{$DEFINE Delphi_1}
	{$DEFINE Delphi_1_UP}
{$ENDIF}

{$IFDEF VER90}
	{$DEFINE Delphi_2}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
{$ENDIF}

{$IFDEF VER100}
	{$DEFINE Delphi_3}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
{$ENDIF}

{$IFDEF VER120}
	{$DEFINE Delphi_4}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
{$ENDIF}

{$IFDEF VER130}
	{$DEFINE Delphi_5}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
{$ENDIF}

{$IFDEF VER140}
	{$DEFINE Delphi_6}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
{$ENDIF}

{$IFDEF VER150}
	{$DEFINE Delphi_7}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
{$ENDIF}

{$IFDEF VER160}
	{$DEFINE Delphi_8_DOTNET}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
{$ENDIF}

{$IFDEF VER170}
	{$DEFINE Delphi_2005}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
{$ENDIF}

{$IFDEF VER180}
	{$DEFINE Delphi_2006}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
{$ENDIF}

{$IFDEF VER185}
	{$DEFINE Delphi_2007}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
{$ENDIF}

{$IFDEF VER190}
	{$DEFINE Delphi_2007_DOTNET}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
{$ENDIF}

{$IFDEF VER200}
	{$DEFINE Delphi_2009}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
{$ENDIF}

{$IFDEF VER210}
	{$DEFINE Delphi_2010}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
{$ENDIF}

{$IFDEF VER220}
	{$DEFINE Delphi_XE}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
{$ENDIF}

{$IFDEF VER230}
	{$DEFINE Delphi_XE2}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
{$ENDIF}

{$IFDEF VER240}
	{$DEFINE Delphi_XE3}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
{$ENDIF}

{$IFDEF VER250}
	{$DEFINE Delphi_XE4}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
	{$DEFINE Delphi_XE4_UP}
{$ENDIF}

{$IFDEF VER260}
	{$DEFINE Delphi_XE5}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
	{$DEFINE Delphi_XE4_UP}
	{$DEFINE Delphi_XE5_UP}
{$ENDIF}

{$IFDEF VER265}
	{$DEFINE AppMethod_1}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
	{$DEFINE Delphi_XE4_UP}
	{$DEFINE Delphi_XE5_UP}
	{$DEFINE AppMethod_1_UP}
{$ENDIF}

{$IFDEF VER270}
	{$DEFINE Delphi_XE6}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
	{$DEFINE Delphi_XE4_UP}
	{$DEFINE Delphi_XE5_UP}
	{$DEFINE AppMethod_1_UP}
	{$DEFINE Delphi_XE6_UP}
{$ENDIF}

{$IFDEF VER280}
	{$DEFINE Delphi_XE7}
	{$DEFINE Delphi_1_UP}
	{$DEFINE Delphi_2_UP}
	{$DEFINE Delphi_3_UP}
	{$DEFINE Delphi_4_UP}
	{$DEFINE Delphi_5_UP}
	{$DEFINE Delphi_6_UP}
	{$DEFINE Delphi_7_UP}
	{$DEFINE Delphi_8_DOTNET_UP}
	{$DEFINE Delphi_2005_UP}
	{$DEFINE Delphi_2006_UP}
	{$DEFINE Delphi_2007_UP}
	{$DEFINE Delphi_2007_DOTNET_UP}
	{$DEFINE Delphi_2009_UP}
	{$DEFINE Delphi_2010_UP}
	{$DEFINE Delphi_XE_UP}
	{$DEFINE Delphi_XE2_UP}
	{$DEFINE Delphi_XE3_UP}
	{$DEFINE Delphi_XE4_UP}
	{$DEFINE Delphi_XE5_UP}
	{$DEFINE AppMethod_1_UP}
	{$DEFINE Delphi_XE6_UP}
	{$DEFINE Delphi_XE7_UP}
{$ENDIF}
